#!/usr/bin/env bash

IMAGE_NAME="hippo-latent-worker"

case $1 in
    iron)
        TAG=$1
        ;;
    jazzy)
        TAG=$1
        ;;
    *)
        echo "Unknown tag."
        exit 1
        ;;
esac

echo "Building $IMAGE_NAME for $TAG"
docker buildx build --build-arg "ROS_DISTRO=$1" ./worker -t $IMAGE_NAME:$TAG

docker tag $IMAGE_NAME:$TAG lennartalff/$IMAGE_NAME:$TAG
docker push lennartalff/$IMAGE_NAME:$TAG
