#!/usr/bin/env bash


tmp=$(uname -m)
case $tmp in
    aarch64)
        ARCH=arm64
        ;;
    x86_64)
        ARCH=amd64
        ;;
    *)
        echo "Unhandled architecture: $tmp"
        exit 1
        ;;
esac

case $1 in
    iron)
        TAG=$1
        ;;
    jazzy)
        TAG=$1
        ;;
    *)
        echo "Unknown tag. <$1>"
        exit 1
        ;;
esac

IMAGE_NAME="hippo-latent-worker-$ARCH"
echo "Building $IMAGE_NAME for $TAG"
docker buildx build --pull --build-arg "ROS_DISTRO=$1" ./worker -t $IMAGE_NAME:$TAG

docker tag $IMAGE_NAME:$TAG lennartalff/$IMAGE_NAME:$TAG
docker push lennartalff/$IMAGE_NAME:$TAG
